// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "reto4-20190921163645-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://reto4-20190921163645-hostingbucket-dev.s3-website-us-east-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-east-1:9ca428c2-a142-4048-b840-38749e726579",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_1LgM0p9Ub",
    "aws_user_pools_web_client_id": "9trknb3o9tu2drm8emnbblcrk",
    "oauth": {},
    "aws_user_files_s3_bucket": "reto426282917d98c46ebadb889980ce12f6e-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "apic20dc1ad",
            "endpoint": "https://pgx36wfkge.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
